"""empty message

Revision ID: de49fb95eaa3
Revises: 36312c52dd51
Create Date: 2021-12-17 11:37:49.842657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de49fb95eaa3'
down_revision = '36312c52dd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('info_link', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('recently_played', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recently_played')
    op.drop_column('media', 'info_link')
    # ### end Alembic commands ###
