"""empty message

Revision ID: 5fb809ac43c2
Revises: bc15e4a8216f
Create Date: 2021-12-21 08:20:02.584458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb809ac43c2'
down_revision = 'bc15e4a8216f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recently_played')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recently_played', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
