"""empty message

Revision ID: 29079c89811b
Revises: de49fb95eaa3
Create Date: 2021-12-17 12:04:40.523279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29079c89811b'
down_revision = 'de49fb95eaa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('hashed_id', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('hashed_id', sa.String(), nullable=True))
    op.add_column('media', sa.Column('hashed_id', sa.String(), nullable=True))
    op.add_column('playlists', sa.Column('hashed_id', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'duration')
    op.drop_column('playlists', 'hashed_id')
    op.drop_column('media', 'hashed_id')
    op.drop_column('artists', 'hashed_id')
    op.drop_column('albums', 'hashed_id')
    # ### end Alembic commands ###
