"""empty message

Revision ID: 54fedc35a818
Revises: 61e976a59832
Create Date: 2021-12-23 15:40:10.288117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fedc35a818'
down_revision = '61e976a59832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.drop_column('playlists', 'image')
    # ### end Alembic commands ###
