"""empty message

Revision ID: bc15e4a8216f
Revises: dce9e3fe4a72
Create Date: 2021-12-20 10:28:41.552636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc15e4a8216f'
down_revision = 'dce9e3fe4a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('image', sa.Text(), nullable=True))
    op.drop_column('albums', 'album_image')
    op.add_column('artists', sa.Column('title', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('image', sa.Text(), nullable=True))
    op.drop_column('artists', 'name')
    op.drop_column('artists', 'artist_image')
    op.add_column('media', sa.Column('image', sa.Text(), nullable=True))
    op.drop_column('media', 'media_image')
    op.add_column('tracks', sa.Column('image', sa.Text(), nullable=True))
    op.drop_column('tracks', 'track_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('track_image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('tracks', 'image')
    op.add_column('media', sa.Column('media_image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('media', 'image')
    op.add_column('artists', sa.Column('artist_image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'image')
    op.drop_column('artists', 'title')
    op.add_column('albums', sa.Column('album_image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('albums', 'image')
    # ### end Alembic commands ###
