"""empty message

Revision ID: 9ec0587be32d
Revises: 29079c89811b
Create Date: 2021-12-17 15:02:12.318409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec0587be32d'
down_revision = '29079c89811b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
